# Generated by Django 3.1.3 on 2020-11-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerMod',
        ),
    ]
