# Generated by Django 3.1.3 on 2020-11-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201118_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermod',
            name='tags',
        ),
        migrations.AddField(
            model_name='productmod',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
