# Generated by Django 3.1.3 on 2020-11-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201118_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmod',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
