# Generated by Django 3.1.3 on 2020-11-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201118_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermod',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
